arb-dir: lib/l10n
template-arb-file: app_en.arb
synthetic-package: false
use-escaping: true
format: true
output-localization-file: app_localizations.g.dart
untranslated-messages-file: lib/l10n/untranslated.txt