name: starter
description: A ready-to-use Flutter project for Android and iOS.
repository: https://github.com/maelchiotti/flutter_starter
documentation: https://github.com/maelchiotti/flutter_starter/wiki
topics:
  - starter
  - template
  - ready-to-use
  - project

version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  go_router: ^10.1.2
  hooks_riverpod: ^2.4.0
  icons_launcher: ^2.1.3
  intl: ^0.18.0
  locale_names: ^1.1.1
  package_info_plus: ^4.1.0
  riverpod_annotation: ^2.1.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.1
  simple_icons: ^7.10.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
