name: starter
description: A ready-to-use Flutter project for Android and iOS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  adaptive_theme: ^3.4.0
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_native_splash: ^2.3.2
  go_router: ^10.1.2
  hooks_riverpod: ^2.4.0
  icons_launcher: ^2.1.3
  package_info_plus: ^4.1.0
  riverpod_annotation: ^2.1.5
  shared_preferences: ^2.2.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true
