name: starter
description: A ready-to-use Flutter project for Android and iOS.
repository: https://github.com/maelchiotti/flutter_starter

version: 0.0.1+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  locale_names: ^1.1.1
  package_info_plus: ^8.0.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.3
  simple_icons: ^10.1.3
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  lint: ^2.3.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/icons/